### PR TITLE
Parity with simple-peer 9.10.0

### PR DESCRIPTION
**Pull request by dmotz**
These changes bring this fork up to date with recent changes in the upstream ([cdad35fb2797c60b61689a539e420a1e3c4fa434](https://github.com/feross/simple-peer/commit/cdad35fb2797c60b61689a539e420a1e3c4fa434), [0e70f43d51a4eae1eee9f6ca83e1ab5836d3775e](https://github.com/feross/simple-peer/commit/0e70f43d51a4eae1eee9f6ca83e1ab5836d3775e)).

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
good job @dmotz 
this lib has saved my life many times over cause i needed bundler support.
hope this PR can be merged and pushed out to npm as a new release @mitschabaude 
thank you both 🙏🙏🙏

**Comment by mitschabaude** [comment]
Nice, will merge

**Comment by mitschabaude** [comment]
Hi, so I looked at this in more detail and concluded that I'll do it in a slightly different way.

I didn't like that this PR introduced completely new commits, I'd rather be able to just keep merging the upstream `simple-peer` into this package while resolving any conflicts that may arise.

So I did just that, I pulled the current version of simple peer in. I also pushed an update to npm. From now on, I always want to use the *same* version number as `simple-peer` so that it becomes clear how up to date with it we are. This means that this time, there is a jump from version `1.0.0` to version `9.10.0` in the package

**Comment by mitschabaude** [comment]
A thing I've changed to facilitate continuing updates is to remove the minified `simplepeer.min.js`, it's just unnecessary headaches to keep maintaining that. The minified file is in the npm package though.

New npm version of `simple-peer-light` is already published btw

**Comment by mitschabaude** [comment]
I'll close this now, thanks a lot for helping me keep this library up to date!

I'll be happy to merge future "parity" PRs, but let's stay as close as possible to the commit history of upstream `simple-peer`.

**Pull request closed without merging**
